// This autogenerated skeleton file illustrates one way to adapt a synchronous
// interface into an asynchronous interface. You should copy it to another
// filename to avoid overwriting it and rewrite as asynchronous any functions
// that would otherwise introduce unwanted latency.

#include "datecService.h"
#include <thrift/protocol/TBinaryProtocol.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::async;

class datecServiceAsyncHandler : public datecServiceCobSvIf {
 public:
  datecServiceAsyncHandler() {
    syncHandler_ = std::auto_ptr<datecServiceHandler>(new datecServiceHandler);
    // Your initialization goes here
  }
  virtual ~datecServiceAsyncHandler();

  void stringInfo(::apache::thrift::stdcxx::function<void(std::string const& _return)> cob, const std::string& s) {
    std::string _return;
    syncHandler_->stringInfo(_return, s);
    return cob(_return);
  }

  void heart(::apache::thrift::stdcxx::function<void()> cob, const std::string& s) {
    syncHandler_->heart(s);
    return cob();
  }

 protected:
  std::auto_ptr<datecServiceHandler> syncHandler_;
};

