/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dc_CONSTANTS_H
#define dc_CONSTANTS_H

#include "dc_types.h"



class dcConstants {
 public:
  dcConstants();

};

extern const dcConstants g_dc_constants;



#endif
